
sec: section10
# logging:
#   level:
#     org:
#       springframework:
#         r2dbc: TRACE

server:
    port: 8080

spring:
  application:
    name: "webflux-sandbox"
  profiles:
    active: "prod"
        
    
#uncomment for mysql 
#    datasource:
#        url: jdbc:mysql://localhost:3306/accountsdb
#        username: root
#        password: root
#    jpa: 
#        show-sql: true
#    sql:
#      init:
#        mode: always
#
#end of mysql

#for H2
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    name: userdb
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///userdb
    username: sa
    password: ''
  sql:
    init:
      data-locations: classpath:sql/data.sql
#
## end of H2

  