@startuml Request Validation Flow

actor Client
participant "CustomerController" as Controller
participant "RequestValidator" as Validator
participant "ApplicationExceptions" as Exceptions
participant "ApplicationExceptionHandler" as ExceptionHandler

Client -> Controller: POST /customers with CustomerDTO
activate Controller

Controller -> Controller: saveCustomer(Mono<CustomerDTO>)
activate Controller #DarkSalmon

Controller -> Validator: transform(RequestValidator.validate())
activate Validator

Validator -> Validator: mono.filter(hasName())
note right: Checks if name is not null

alt Name is null
    Validator -> Exceptions: missingName()
    activate Exceptions
    Exceptions --> Validator: Mono.error(InvalidInputException)
    deactivate Exceptions
    Validator --> Controller: Error Mono
    Controller --> ExceptionHandler: InvalidInputException thrown
    activate ExceptionHandler
    ExceptionHandler --> Client: HTTP 400 with ProblemDetail
    deactivate ExceptionHandler
else Name is not null
    Validator -> Validator: filter(hasValidEmail())
    note right: Checks if email is not null and contains @
    
    alt Email is invalid
        Validator -> Exceptions: missingEmail()
        activate Exceptions
        Exceptions --> Validator: Mono.error(InvalidInputException)
        deactivate Exceptions
        Validator --> Controller: Error Mono
        Controller --> ExceptionHandler: InvalidInputException thrown
        activate ExceptionHandler
        ExceptionHandler --> Client: HTTP 400 with ProblemDetail
        deactivate ExceptionHandler
    else Email is valid
        Validator --> Controller: Valid CustomerDTO Mono
        Controller -> Controller: as(service::saveCustomer)
        note right: Passes validated CustomerDTO to service
        Controller --> Client: HTTP response with CustomerDTO
    end
end

deactivate Validator
deactivate Controller #DarkSalmon
deactivate Controller

@enduml